config/routes.rb
Rails.application.routes.draw do
  root to: "wires#concept"
  get 'izawa', to: 'wires#izawa'
  patch 'reset', to: 'wires#reset'

  resources :wires,only: [:new, :create, :show, :edit, :update] do
    member do
      get 'izawachumon'
      get '_izawachumon'
      get 'conceptzaiko'
      patch 'update2'
    end
  end


end
 

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/iro.rb
class Iro < ActiveHash::Base
  self.data = [
    { id: 1, name: '色' },
    { id: 2, name: '黒' },
    { id: 3, name: '赤' },
    { id: 4, name: '白' }
  ]

  include ActiveHash::Associations
  has_many :wires
end

app/models/kei.rb
class Kei < ActiveHash::Base
  self.data = [
    { id: 1, name: '径' },
    { id: 2, name: '#12' },
    { id: 3, name: '#14' }
  ]

  include ActiveHash::Associations
  has_many :wires
end

app/models/wire.rb
class Wire < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :kei
  belongs_to :iro

  validates :hinban, presence: true
  validates :chumon, presence: true
  validates :chumonlog, presence: true
  validates :zaiko, presence: true
  validates :zaikolog, presence: true
  validates :kei_id, presence: true, numericality: { other_than: 1 }
  validates :iro_id, presence: true, numericality: { other_than: 1 }
  validates :nagasa, presence: true
  validates :tanka, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth


  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
    end
  end
end

app/controllers/wires_controller.rb
class WiresController < ApplicationController
  def concept
    @wires = Wire.all.order(:hinban)
  end

  def izawa
    @wires = Wire.all.order(:hinban)
  end

  def izawachumon
    @wire = Wire.find(params[:id])
    @wire.chumon = []
  end

  def conceptzaiko
    @wire = Wire.find(params[:id])
    @wire.zaiko = []
  end

  def new
    @wire = Wire.new
  end

  def create
    @wire = Wire.create(wire_params)
    if @wire.save
      redirect_to izawa_path
    else
      render :new
    end
  end

  def update
    @wire = Wire.find(params[:id])
    @wire.update(wire_params)
    @wire.zaiko = @wire.zaiko - @wire.chumon
    @wire.zaikolog = @wire.zaiko
    @wire.save
    redirect_to izawa_path
  end

  def show
    @wire = Wire.find(params[:id])
  end

  def edit
    @wire = Wire.find(params[:id])
  end

  def update2
    @wire = Wire.find(params[:id])
    @wire.update(wire_params)
    @wire.zaiko = @wire.zaikolog + @wire.zaiko
    @wire.zaikolog = @wire.zaiko
    @wire.save
    redirect_to root_path
  end

  def reset
    Wire.update_all(chumon: 0)
    redirect_to izawa_path
  end

  private

  def wire_params
    params.require(:wire).permit(:hinban, :kei_id, :iro_id, :nagasa, :tanka, :chumon, :chumonlog, :zaiko, :zaikolog)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/wires_helper.rb
module WiresHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ConceptIzawa</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= yield %>
  </body>
</html>

app/views/wires/_izawachumon.erb
<%= form_with model: @wire, local: true do |f| %>
  <div class="wire-box">
    <%= f.text_field :chumon, autofocus: true, class:"chumon", placeholder:"確定注文数" %>
  <%= f.submit "確定" ,class:"btn" %>
<% end %>
 

app/views/wires/concept.html.erb
      <header class="header">
      <div class="concept-var">
        <div class="concept-logo">
              <%= link_to "CONCEPT", root_path, class: :concept__btn %>
              </div>
              <div class="izawa-logo">
              <%= link_to "井澤金属→", izawa_path, class: :izawa__btn %>
              </div>
        </div>
      </div>
    </header>
<% if @wires.any?{ |wires| wires.zaiko < 0} %>
    <div class="zettaiseisan">
    17:30までに絶対生産
    </div>
    <% else %>
    <div class="kaetteyosi">帰ってヨシ！</div>
    <% end %>
    <div class="topspace">
    </div>

<% @wires.each do |wire| %>
<% if wire.zaiko.negative? %>

  <div class="concept-seisan">
<% if wire.iro_id == 3 %>
  <div class="hidari">
<div class="wirekei"><%= "#{wire.kei.name}" %></div>
 <div class="wirered"><%= "L#{wire.nagasa}" %></div>
</div>
    <div class="concept-hinban">
      <%= wire.hinban %>
    </div>
        <div class="concept-hitsuyousu">
        <% hitsuyousu = wire.zaiko %>
        <font color=red><%= "#{hitsuyousu}" %></font>
    </div>
    <div class="concept-hensyu-btn">
      <%= link_to "編集",conceptzaiko_wire_path(wire.id), class: :wire_btn %>
    </div> 
  </div>
  <% elsif wire.iro_id == 2%>
    <div class="hidari">
<div class="wirekei"><%= "#{wire.kei.name}" %></div>
 <div class="wireblack"><%= "L#{wire.nagasa}" %></div>
</div>
    <div class="concept-hinban">
      <%= wire.hinban %>
    </div>
        <div class="concept-hitsuyousu">
        <% hitsuyousu = wire.zaiko %>
        <font color=red><%= "#{hitsuyousu}" %></font>
    </div>
    <div class="concept-hensyu-btn">
      <%= link_to "編集",conceptzaiko_wire_path(wire.id), class: :wire_btn %>
    </div> 
  </div>
  <% else wire.iro_id == 4%>
    <div class="hidari">
<div class="wirekei"><%= "#{wire.kei.name}" %></div>
 <div class="wirewhite"><%= "L#{wire.nagasa}" %></div>
</div>
    <div class="concept-hinban">
      <%= wire.hinban %>
    </div>
        <div class="concept-hitsuyousu">
        <% hitsuyousu = wire.zaiko %>
        <font color=red><%= "#{hitsuyousu}" %></font>
    </div>
    <div class="concept-hensyu-btn">
      <%= link_to "編集",conceptzaiko_wire_path(wire.id), class: :wire_btn %>
    </div> 
  </div>
  <% end %>
<% end %>
<% end %>

app/views/wires/conceptseisan.html.erb
<h1>生産数入力ページ</h1>

<%= form_with model: @wire, url:update2_wire_path, local: true do |f| %>
  <div class="wire-box">
    生産数<%= f.text_field :seisan, autofocus: true,class:"seisan", placeholder:"生産数" %>
  <%= f.submit "確定" ,class:"btn" %>
<% end %>

app/views/wires/conceptzaiko.html.erb
      <header class="header">
      <div class="concept-var">
        <div class="concept-logo">
              <%= link_to "CONCEPT", root_path, class: :concept__btn %>
              </div>
              <div class="izawa-logo">
              <%= link_to "井澤金属→", izawa_path, class: :izawa__btn %>
              </div>
        </div>
      </div>
    </header>
        <div class="zettaiseisan">
    17:30までに絶対生産
    </div>
     <div class="topspace">
    </div>

      <div class="concept-seisan">
<% if @wire.iro_id == 3 %>
  <div class="hidari">
<div class="wirekei"><%= "#{@wire.kei.name}" %></div>
 <div class="wirered"><%= "L#{@wire.nagasa}" %></div>
</div>
    <div class="concept-hinban">
      <%= @wire.hinban %>
    </div>
        <div class="concept-hitsuyousu">
        <% hitsuyousu = @wire.zaikolog %>
        <font color=red><%= "#{hitsuyousu}" %></font>
    </div>


  <% elsif @wire.iro_id == 2%>
    <div class="hidari">
<div class="wirekei"><%= "#{@wire.kei.name}" %></div>
 <div class="wireblack"><%= "L#{@wire.nagasa}" %></div>
</div>
    <div class="concept-hinban">
      <%= @wire.hinban %>
    </div>
        <div class="concept-hitsuyousu">
        <% hitsuyousu = @wire.zaikolog %>
        <font color=red><%= "#{hitsuyousu}" %></font>
    </div>


  <% else @wire.iro_id == 4%>
    <div class="hidari">
<div class="wirekei"><%= "#{@wire.kei.name}" %></div>
 <div class="wirewhite"><%= "L#{@wire.nagasa}" %></div>
</div>
    <div class="concept-hinban">
      <%= @wire.hinban %>
    </div>
        <div class="concept-hitsuyousu">
        <% hitsuyousu = @wire.zaikolog %>
        <font color=red><%= "#{hitsuyousu}" %></font>
    </div>
  <% end %>
  <%= form_with model: @wire, url:update2_wire_path, local: true do |f| %>
  <div class="wire-box">
    <%= f.text_field :zaiko, autofocus: true,class:"conceptzaikoform", placeholder:"生産数入力" %>
  <%= f.submit "確定" ,class:"btn" %>
   </div>
<% end %>
 


    

app/views/wires/edit.html.erb
      <header class="header">
      <div class="concept-var">
        <div class="concept-logo">
              <%= link_to "井澤金属", izawa_path, class: :concept__btn %>
              </div>
              <div class="izawa-logo">
              <%= link_to "CONCEPT→", root_path, class: :izawa__btn %>
              </div>
        </div>
      </div>
    </header>
        <div class="izawatopspace">
      <div class="shinkihin"><%= link_to '新規品追加',new_wire_path,class: :izawa__shinki %></div>
      <div class="ichiran">注文書作成</div>
      <div class="reset"><%= link_to '0リセット',reset_path,class: :izawa__riset ,method: :patch  %></div>
    </div>
    <div class="newspace"></div>

    <div class="newspace2">品番編集</div>

  <div class="newwire-box">
    <%= form_with model: @wire,  local: true do |f| %>
    <%= f.text_field :hinban, class:"newform", placeholder:"品番名" %>
    <%= f.collection_select(:kei_id, Kei.all, :id, :name, {}, {class:"newkei"}) %>
    <%= f.collection_select(:iro_id, Iro.all, :id, :name, {}, {class:"newkei"}) %>
    <%= f.text_field :nagasa, class:"newformmini", placeholder:"L寸" %>
    <%= f.text_field :tanka, class:"newformmini", placeholder:"単価" %>
    <%= f.text_field :chumon, class:"newform3", placeholder:"注文数" %>
    <%= f.text_field :chumonlog, class:"newform3", placeholder:"注文log" %>
    <%= f.text_field :zaiko, class:"newform3", placeholder:"在庫数" %>
    <%= f.text_field :zaikolog, class:"newform3", placeholder:"在庫log" %>
    <%= f.submit "変更" ,class:"newshinkibtn" %>
  </div>
  
<% end %>

app/views/wires/index.html.erb
<h1>井澤金属側</h1>
<%= link_to 'コンセプト側へ',root_path %>
<%= link_to '新規品作成',new_wire_path %>
<%= link_to '0リセット',reset_path, method: :patch  %>

<% @wires.each do |wire| %>
  <div class="article">
    <div class="article-genre">
      <%= wire.hinban %>
    </div>
    <div class="article-title">
    確定注文: <%= wire.chumon %>
    </div>
    <div class="article-title">
    　在庫　: <%= wire.seisan %>
    </div>
    <div class="article-text">
    　不足　:<%= wire.seisan - wire.chumon %>
    </div>
    <div class="prototype__manage">
      <%= link_to "編集", edit_wire_path(wire.id), class: :wire_btn %>
    </div>
  </div>
<% end %>

app/views/wires/izawa.html.erb
      <header class="header">
      <div class="concept-var">
        <div class="concept-logo">
              <%= link_to "井澤金属", izawa_path, class: :concept__btn %>
              </div>
              <div class="izawa-logo">
              <%= link_to "CONCEPT→", root_path, class: :izawa__btn %>
              </div>
        </div>
      </div>
    </header>
    <div class="izawatopspace">
      <div class="shinkihin"><%= link_to '新規品追加',new_wire_path,class: :izawa__shinki %></div>
      <div class="ichiran">注文書作成</div>
      <div class="reset"><%= link_to '0リセット',reset_path,class: :izawa__riset ,method: :patch  %></div>
    </div>
        <div class="izawaspace">
        <div class="izawamigispace"></div>
        <div class="izawahinban"><div class ="izawawires">品番</div></div>
        <div class="izawazaiko"><div class ="izawawires">在庫</div></div>
        <div class="izawachumon"><div class ="izawawires">注文数</div></div>
        <div class="izawahidarispace"></div>
        </div>

      <% @wires.each do |wire| %>
        <div class="izawaspace2">
        <div class="izawamigispace"></div>
        <div class="izawahinban2"><%= link_to "#{wire.hinban}", edit_wire_path(wire.id), class: :izawafontsize %></div>
        <div class="izawazaiko2">
        <% if wire.zaiko.negative? %>
          <div class="izawafontsize"><font color=red><%= wire.zaiko  %></font></div>
        <% else %>
           <div class="izawafontsize"><%= wire.zaiko %></div>
         <% end %>
          </div>
        <div class="izawachumon2"><%= link_to "#{wire.chumon}",izawachumon_wire_path(wire.id), class: :izawafontsize %></div>
        <div class="izawahidarispace">
          <div class="izawa_wire_btn_waku">
          <%= link_to "編集",izawachumon_wire_path(wire.id),  class: :izawa_wire_btn %>
          </div>
        </div>
        </div>
      <% end %>

app/views/wires/izawachumon.erb
      <header class="header">
      <div class="concept-var">
        <div class="concept-logo">
              <%= link_to "井澤金属", izawa_path, class: :concept__btn %>
              </div>
              <div class="izawa-logo">
              <%= link_to "CONCEPT→", root_path, class: :izawa__btn %>
              </div>
        </div>
      </div>
    </header>
    <div class="izawatopspace">
      <div class="shinkihin"><%= link_to '新規品追加',new_wire_path,class: :izawa__shinki %></div>
      <div class="ichiran">注文書作成</div>
      <div class="reset"><%= link_to '0リセット',reset_path,class: :izawa__riset ,method: :patch  %></div>
    </div>
        <div class="izawaspace">
        <div class="izawamigispace"></div>
        <div class="izawahinban"><div class ="izawawires">品番</div></div>
        <div class="izawazaiko"><div class ="izawawires">在庫</div></div>
        <div class="izawachumon"><div class ="izawawires">注文数</div></div>
        <div class="izawahidarispace"></div>
        </div>

        <div class="izawaspace2">
        <div class="izawamigispace"></div>
        <div class="izawahinban2"><%= "#{@wire.hinban}"%></div>
        <div class="izawazaiko2">
        <% if @wire.zaiko.negative? %>
          <div class="izawafontsize"><font color=red><%= @wire.zaiko  %></font></div>
        <% else %>
           <div class="izawafontsize"><%= @wire.zaiko %></div>
         <% end %>
          </div>
        <div class="izawachumon3">
            <%= form_with model: @wire, local: true do |f| %>
            <%= f.text_field :chumon, autofocus: true, class:"izawachumonform3", placeholder:"確定注文数" %> 
           <% end %> 
        </div>

        <div class="izawahidarispace2">

        </div>
        </div>





 

app/views/wires/new.html.erb
      <header class="header">
      <div class="concept-var">
        <div class="concept-logo">
              <%= link_to "井澤金属", izawa_path, class: :concept__btn %>
              </div>
              <div class="izawa-logo">
              <%= link_to "CONCEPT→", root_path, class: :izawa__btn %>
              </div>
        </div>
      </div>
    </header>
        <div class="izawatopspace">
      <div class="shinkihin"><%= link_to '新規品追加',new_wire_path,class: :izawa__shinki %></div>
      <div class="ichiran">注文書作成</div>
      <div class="reset"><%= link_to '0リセット',reset_path,class: :izawa__riset ,method: :patch  %></div>
    </div>
    <div class="newspace"></div>

    <div class="newspace2">新規品追加</div>

  <div class="newwire-box">
    <%= form_with model: @wire,  local: true do |f| %>
    <%= f.text_field :hinban,autofocus: true,class:"newform", placeholder:"品番名" %>
    <%= f.collection_select(:kei_id, Kei.all, :id, :name, {}, {class:"newkei"}) %>
    <%= f.collection_select(:iro_id, Iro.all, :id, :name, {}, {class:"newkei"}) %>
    <%= f.text_field :nagasa, class:"newformmini", placeholder:"L寸" %>
    <%= f.text_field :tanka, class:"newformmini", placeholder:"単価" %>
    <%= f.submit "登録" ,class:"newshinkibtn" %>
  </div>
  
<% end %>

app/views/wires/show.html.erb
<h1>詳細ページ</h1>
<%= link_to "編集", edit_wire_path(@wire.id), class: :wire_btn %>